import Link from "next/link";

const content: Record<string, { title: string; intro: string; sections: [string,string][] }> = {
  privacidad:{title:"Política de privacidad",intro:"Vigente desde el 11 de agosto de 2026.",sections:[["Datos que usamos","Tratamos el correo, las preferencias alimentarias, el tamaño del hogar, el uso del producto y el estado de la suscripción cuando son necesarios para prestar el servicio. No almacenamos números de tarjeta ni datos bancarios."],["Para qué los usamos","Usamos esos datos para autenticarte, preparar y guardar tu semana, administrar el acceso, atender incidencias y conocer si el servicio funciona correctamente. Menú Low Carb Latino no utiliza inteligencia artificial generativa ni envía tus preferencias a un proveedor de IA."],["Proveedores","Hotmart procesa la compra; Supabase aloja la cuenta y los datos; Vercel publica la app; Resend entrega los correos de acceso. Cada proveedor trata únicamente los datos necesarios para su función."],["Conservación y seguridad","Conservamos la información mientras la cuenta o una obligación operativa o legal lo requiera. Los registros financieros mínimos pueden conservarse sin vinculación directa a la cuenta cuando exista una obligación contable o de prevención de fraude. Aplicamos acceso restringido, cifrado en tránsito y reglas de base de datos para separar las cuentas."],["Tus decisiones y derechos","Desde Cuenta y privacidad dentro de la app puedes descargar una copia de tus datos o eliminar la cuenta. También puedes corregir tus preferencias en el producto. Las preferencias de marketing, cuando existan, serán opcionales y separadas del servicio."],["Edad mínima","El servicio está dirigido a personas mayores de 18 años. No recopilamos deliberadamente datos de menores."]]},
  terminos:{title:"Términos de servicio",intro:"Vigentes desde el 10 de agosto de 2026.",sections:[["Servicio","Menú Low Carb Latino organiza cenas, recetas y listas de compras. Es una herramienta informativa y no presta atención médica ni promete resultados de salud."],["Cuenta y acceso","El acceso es personal y se verifica mediante un enlace seguro enviado al correo utilizado en la compra. No compartas ese enlace ni permitas el uso de tu cuenta por terceros."],["Suscripción","Hotmart muestra el plan, precio, moneda, fecha del primer cobro y frecuencia de renovación antes de confirmar. La suscripción se renueva hasta que la canceles desde tu cuenta de comprador."],["Disponibilidad y cambios","Podemos corregir errores, mantener o actualizar el servicio. Si una interrupción afecta el acceso, conservaremos el historial necesario para restablecerlo de forma segura."],["Uso responsable","Debes revisar ingredientes, alergias, etiquetas y recomendaciones profesionales aplicables a tu situación antes de preparar o consumir una receta."]]},
  reembolso:{title:"Cancelación y reembolsos",intro:"Condiciones aplicables a las suscripciones procesadas por Hotmart.",sections:[["Prueba gratuita","El checkout muestra la duración de la prueba, el precio y la fecha del primer cobro. Si cancelas antes de esa fecha, Hotmart detiene la renovación y no realiza el siguiente cobro."],["Cómo cancelar","Entra en Mis compras de Hotmart, abre Menú Low Carb Latino, selecciona la configuración de pago y confirma Cancelar suscripción. La cancelación impide cobros futuros."],["Acceso después de cancelar","Conservarás el acceso hasta la fecha indicada por Hotmart para el período de prueba o período ya pagado, salvo que corresponda un reembolso o contracargo."],["Reembolsos","La garantía configurada es de 7 días. En una suscripción, Hotmart aplica la posibilidad de reembolso a la transacción inicial cuando la solicitud cumple las condiciones y el plazo mostrado en el checkout. Cancelar por sí solo no devuelve automáticamente un pago."],["Canal de gestión","Las cancelaciones y solicitudes de reembolso se tramitan desde la cuenta de comprador o los canales oficiales de Hotmart, donde queda registrado el estado de la transacción."]]},
  disclaimer:{title:"Aviso alimentario",intro:"Menú Low Carb Latino organiza información; no sustituye atención profesional.",sections:[["Sin consejo médico","La app no diagnostica, trata ni garantiza pérdida de peso o control de glucosa."],["Alergias y restricciones","Revisa siempre ingredientes, etiquetas y posibles contaminaciones cruzadas."],["Decisiones personales","Consulta a un profesional ante embarazo, enfermedad, medicación o necesidades clínicas."]]},
};

export function LegalContent({kind}:{kind:keyof typeof content}){
  const page=content[kind];
  return <main className="legal-page"><Link href="/">← Volver a Menú Low Carb Latino</Link><p className="kicker">INFORMACIÓN LEGAL</p><h1>{page.title}</h1><p className="legal-intro">{page.intro}</p>{page.sections.map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}<p className="legal-contact"><a href="https://consumer.hotmart.com/purchase">Abrir Mis compras en Hotmart</a> · <a href="https://help.hotmart.com/es/article/115002183968/-como-cancelar-mi-suscripcion-">Ver instrucciones oficiales de cancelación</a></p></main>
}
